drop table if exists member CASCADE;
create table member
(
    id bigint generated by default as identity,
    name varchar(255),
    address varchar(255),
    reg_date varchar(20),
    primary key (id)
)